### ISSUE TITLE
Hi, I have a problem implementing your predict.py

### ISSUE THREAD

**Issue by Shuaaai** [keisks/robsut-wrod-reocginiton#1]
Firstly, I appreciate your sprits for sharing your code. It helped me a lot. But when I am trying to run predict.py, I am in trouble with the command "python predict.py -m models/train_j-INT_n-JUMBLE_u-650_batch-20_ep-10_model.h5". I have prepared the file and the command ends with the error information as follows:
    
  ```
  Traceback (most recent call last):
  File "predict.py", line 135, in <module>
    model = load_model(model_file)
  File "C:\Python35\lib\site-packages\keras\models.py", line 280, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "C:\Python35\lib\site-packages\keras\optimizers.py", line 79, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (2600,) not compatible with provided weight shape (650, 10002)

```
    
It seems like the shape does not match. I am a beginner and I can't figure out what is going wrong. If you can give me some advice, it will help me a lot. Looking forword to your reply.

**Comment by keisks** [comment]
I updated the model file and added prerequisite information. Hope this helps.
